# generated by datamodel-codegen:
#   filename:  transaction.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType


class Source(StrEnum):
    """
    How this transaction entered the system.
    """

    bank_statement = "bank_statement"
    receipt = "receipt"
    amazon_order = "amazon_order"
    manual = "manual"


class IngestionType(StrEnum):
    """
    Input format or importer used to ingest this transaction.
    """

    ofx = "ofx"
    qfx = "qfx"
    fidelity_csv = "fidelity_csv"
    receipt_img = "receipt_img"
    amazon = "amazon"


class Kind(StrEnum):
    """
    User-facing transaction kind.
    """

    expense = "expense"
    income = "income"
    transfer = "transfer"
    adjustment = "adjustment"


class Status(StrEnum):
    pending = "pending"
    posted = "posted"
    reconciled = "reconciled"
    void = "void"


class GroupRole(StrEnum):
    """
    How this source record should participate when a transaction group is displayed.
    """

    primary = "primary"
    supporting = "supporting"
    excluded_from_display = "excluded_from_display"


class MatchStatus(StrEnum):
    """
    Current matching state for this transaction record.
    """

    unmatched = "unmatched"
    candidate = "candidate"
    confirmed = "confirmed"
    rejected = "rejected"


class MatchSource(StrEnum):
    """
    How the transaction match or grouping decision was made.
    """

    user = "user"
    model = "model"
    rule = "rule"
    importer = "importer"


NonEmptyString = TypeAliasType("NonEmptyString", Annotated[str, Field(min_length=1)])


class Source1(StrEnum):
    """
    How this allocation was assigned.
    """

    user = "user"
    model = "model"
    rule = "rule"
    receipt = "receipt"


class CategoryAllocation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    category_id: Annotated[str, Field(alias="categoryId", min_length=1)]
    amount: Annotated[
        str,
        Field(
            description="Signed amount allocated to this category.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    confidence: Annotated[
        float | None,
        Field(description="Confidence score when the category was inferred.", ge=0.0, le=1.0),
    ] = None
    source: Annotated[Source1 | None, Field(description="How this allocation was assigned.")] = None


class LineType(StrEnum):
    item = "item"
    tax = "tax"
    tip = "tip"
    service_charge = "service_charge"
    shipping = "shipping"
    fee = "fee"
    discount = "discount"
    return_ = "return"
    other = "other"


class ReceiptItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(min_length=1)] = None
    description: Annotated[
        str,
        Field(description="Normalized, user-facing receipt line item description.", min_length=1),
    ]
    raw_description: Annotated[
        str | None,
        Field(
            alias="rawDescription",
            description="Raw receipt line item description as extracted from the source document.",
            min_length=1,
        ),
    ] = None
    brave_search_result: Annotated[
        str | None,
        Field(
            alias="braveSearchResult",
            description="JSON-encoded Brave Search result summaries containing only title and description fields.",
            min_length=1,
        ),
    ] = None
    quantity: Annotated[float | None, Field(gt=0.0)] = None
    unit_price: Annotated[
        str | None,
        Field(
            alias="unitPrice",
            description="Decimal amount encoded as a string to avoid floating point rounding errors.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    amount: Annotated[
        str,
        Field(
            description="Signed line amount, including discounts or returns when negative.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    discount_amount: Annotated[
        str | None,
        Field(
            alias="discountAmount",
            description="Signed discount amount applied to this item, when a following discount line was merged into it.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    discount_description: Annotated[
        str | None,
        Field(
            alias="discountDescription",
            description="Raw description from a discount line merged into this item.",
            min_length=1,
        ),
    ] = None
    net_amount: Annotated[
        str,
        Field(
            alias="netAmount",
            description="Final item amount after applying any item-level discount amount.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    line_type: Annotated[LineType | None, Field(alias="lineType")] = LineType.item
    category_id: Annotated[str | None, Field(alias="categoryId", min_length=1)] = None
    taxonomy1: Annotated[
        str | None, Field(description="First-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy2: Annotated[
        str | None, Field(description="Second-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy3: Annotated[
        str | None, Field(description="Third-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy4: Annotated[
        str | None, Field(description="Fourth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy5: Annotated[
        str | None, Field(description="Fifth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy6: Annotated[
        str | None, Field(description="Sixth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy7: Annotated[
        str | None, Field(description="Seventh-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy8: Annotated[
        str | None, Field(description="Eighth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy9: Annotated[
        str | None, Field(description="Ninth-level product taxonomy category.", min_length=1)
    ] = None
    confidence: Annotated[
        float | None,
        Field(
            description="Confidence score when the line category or extraction was inferred.",
            ge=0.0,
            le=1.0,
        ),
    ] = None


class ExtractionMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    model: Annotated[str | None, Field(min_length=1)] = None
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    extracted_at: Annotated[AwareDatetime | None, Field(alias="extractedAt")] = None
    raw_text: Annotated[str | None, Field(alias="rawText")] = None


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(min_length=1)] = None
    source_document_id: Annotated[
        str | None,
        Field(
            alias="sourceDocumentId",
            description="Uploaded image, PDF or extraction job identifier.",
            min_length=1,
        ),
    ] = None
    receipt_number: Annotated[str | None, Field(alias="receiptNumber", min_length=1)] = None
    subtotal: Annotated[
        str | None,
        Field(
            description="Decimal amount encoded as a string to avoid floating point rounding errors.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    total: Annotated[
        str | None,
        Field(
            description="Receipt total as shown by the merchant or source document. Usually positive for purchases; transaction amount carries the account-perspective sign.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    items: Annotated[list[ReceiptItem], Field(min_length=1)]
    extraction: ExtractionMetadata | None = None


class Transaction(BaseModel):
    """
    A canonical expense-tracking transaction, optionally enriched with receipt line items and category allocations.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[
        str,
        Field(
            description="Application-level stable identifier for this transaction.", min_length=1
        ),
    ]
    source: Annotated[Source, Field(description="How this transaction entered the system.")]
    ingestion_date: Annotated[
        date | None,
        Field(
            alias="ingestionDate", description="Date this transaction was ingested into the system."
        ),
    ] = None
    ingestion_filename: Annotated[
        str | None,
        Field(
            alias="ingestionFilename",
            description="Source filename or archive member name used to ingest this transaction.",
            min_length=1,
        ),
    ] = None
    ingestion_type: Annotated[
        IngestionType | None,
        Field(
            alias="ingestionType",
            description="Input format or importer used to ingest this transaction.",
        ),
    ] = None
    external_id: Annotated[
        str | None,
        Field(
            alias="externalId",
            description="Importer-provided identifier, if one exists.",
            min_length=1,
        ),
    ] = None
    account_id: Annotated[
        str | None,
        Field(
            alias="accountId",
            description="Account that produced the statement row, when applicable.",
            min_length=1,
        ),
    ] = None
    transaction_date: Annotated[
        date, Field(alias="transactionDate", description="Date the transaction occurred.")
    ]
    posted_date: Annotated[
        date | None,
        Field(
            alias="postedDate",
            description="Date the transaction posted to the account, when different from the transaction date.",
        ),
    ] = None
    payee: Annotated[
        str | None, Field(description="Merchant, counterparty or payer name.", min_length=1)
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Statement-provided transaction description, when separate from the payee."
        ),
    ] = None
    mcc: Annotated[
        str | None,
        Field(
            description="Merchant Category Code extracted from a credit card statement, when available.",
            pattern="^[0-9]{4}$",
        ),
    ] = None
    mcc_description: Annotated[
        str | None,
        Field(
            alias="mccDescription",
            description="Textual description of the Merchant Category Code category, when available.",
            min_length=1,
        ),
    ] = None
    brave_search_result: Annotated[
        str | None,
        Field(
            alias="braveSearchResult",
            description="JSON-encoded Brave Search result summaries containing only title and description fields.",
            min_length=1,
        ),
    ] = None
    amount: Annotated[
        str,
        Field(
            description="Signed transaction amount from the account perspective.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    currency: Annotated[str, Field(description="ISO 4217 currency code.", pattern="^[A-Z]{3}$")]
    kind: Annotated[Kind | None, Field(description="User-facing transaction kind.")] = None
    status: Status | None = Status.posted
    category_allocations: Annotated[
        list[CategoryAllocation] | None,
        Field(
            alias="categoryAllocations",
            description="Budget category splits for the transaction total.",
            validate_default=True,
        ),
    ] = []
    receipt: Annotated[
        Receipt | None, Field(description="Itemized receipt data associated with this transaction.")
    ] = None
    receipt_data_extraction_service: Annotated[
        str | None,
        Field(
            alias="receiptDataExtractionService",
            description="Receipt data extraction service used for this transaction, such as azure-doc-intelligence or gemini-3-flash-lite.",
            min_length=1,
        ),
    ] = None
    receipt_image_extraction_results: Annotated[
        str | None,
        Field(
            alias="receiptImageExtractionResults",
            description="JSON-encoded map of raw receipt image extraction service responses keyed by service name, such as azure-doc-intelligence or gemini.",
            min_length=1,
        ),
    ] = None
    linked_transaction_ids: Annotated[
        list[NonEmptyString] | None,
        Field(
            alias="linkedTransactionIds",
            description="Deprecated pairwise links to other transaction records that represent the same real-world purchase. Prefer transactionGroupId for display grouping.",
        ),
    ] = []
    transaction_group_id: Annotated[
        str | None,
        Field(
            alias="transactionGroupId",
            description="Stable identifier shared by imported transaction records that represent the same real-world transaction. UIs should collapse records with the same group id into one displayed transaction.",
            min_length=1,
        ),
    ] = None
    group_role: Annotated[
        GroupRole | None,
        Field(
            alias="groupRole",
            description="How this source record should participate when a transaction group is displayed.",
        ),
    ] = None
    match_status: Annotated[
        MatchStatus | None,
        Field(
            alias="matchStatus", description="Current matching state for this transaction record."
        ),
    ] = MatchStatus.unmatched
    match_source: Annotated[
        MatchSource | None,
        Field(
            alias="matchSource",
            description="How the transaction match or grouping decision was made.",
        ),
    ] = None
    match_confidence: Annotated[
        float | None,
        Field(
            alias="matchConfidence",
            description="Confidence score for automated or suggested transaction matching.",
            ge=0.0,
            le=1.0,
        ),
    ] = None
    notes: str | None = None
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
