# generated by datamodel-codegen:
#   filename:  transaction.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType


class Source(StrEnum):
    """
    How this transaction entered the system.
    """

    bank_statement = "bank_statement"
    receipt = "receipt"
    manual = "manual"


class Kind(StrEnum):
    """
    User-facing transaction kind.
    """

    expense = "expense"
    income = "income"
    transfer = "transfer"
    adjustment = "adjustment"


class Status(StrEnum):
    pending = "pending"
    posted = "posted"
    reconciled = "reconciled"
    void = "void"


NonEmptyString = TypeAliasType("NonEmptyString", Annotated[str, Field(min_length=1)])


class Source1(StrEnum):
    """
    How this allocation was assigned.
    """

    user = "user"
    model = "model"
    rule = "rule"
    receipt = "receipt"


class CategoryAllocation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    category_id: Annotated[str, Field(alias="categoryId", min_length=1)]
    amount: Annotated[
        str,
        Field(
            description="Signed amount allocated to this category.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    confidence: Annotated[
        float | None,
        Field(description="Confidence score when the category was inferred.", ge=0.0, le=1.0),
    ] = None
    source: Annotated[Source1 | None, Field(description="How this allocation was assigned.")] = None


class LineType(StrEnum):
    item = "item"
    tax = "tax"
    tip = "tip"
    service_charge = "service_charge"
    shipping = "shipping"
    fee = "fee"
    discount = "discount"
    return_ = "return"
    other = "other"


class ReceiptItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(min_length=1)] = None
    description: Annotated[
        str,
        Field(description="Normalized, user-facing receipt line item description.", min_length=1),
    ]
    raw_description: Annotated[
        str | None,
        Field(
            alias="rawDescription",
            description="Raw receipt line item description as extracted from the source document.",
            min_length=1,
        ),
    ] = None
    brave_search_result: Annotated[
        str | None,
        Field(
            alias="braveSearchResult",
            description="JSON-encoded Brave Search result summaries containing only title and description fields.",
            min_length=1,
        ),
    ] = None
    quantity: Annotated[float | None, Field(gt=0.0)] = None
    unit_price: Annotated[
        str | None,
        Field(
            alias="unitPrice",
            description="Decimal amount encoded as a string to avoid floating point rounding errors.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    amount: Annotated[
        str,
        Field(
            description="Signed line amount, including discounts or returns when negative.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    discount_amount: Annotated[
        str | None,
        Field(
            alias="discountAmount",
            description="Signed discount amount applied to this item, when a following discount line was merged into it.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    discount_description: Annotated[
        str | None,
        Field(
            alias="discountDescription",
            description="Raw description from a discount line merged into this item.",
            min_length=1,
        ),
    ] = None
    net_amount: Annotated[
        str | None,
        Field(
            alias="netAmount",
            description="Final item amount after applying any item-level discount amount.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    line_type: Annotated[LineType | None, Field(alias="lineType")] = LineType.item
    category_id: Annotated[str | None, Field(alias="categoryId", min_length=1)] = None
    taxonomy1: Annotated[
        str | None, Field(description="First-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy2: Annotated[
        str | None, Field(description="Second-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy3: Annotated[
        str | None, Field(description="Third-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy4: Annotated[
        str | None, Field(description="Fourth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy5: Annotated[
        str | None, Field(description="Fifth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy6: Annotated[
        str | None, Field(description="Sixth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy7: Annotated[
        str | None, Field(description="Seventh-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy8: Annotated[
        str | None, Field(description="Eighth-level product taxonomy category.", min_length=1)
    ] = None
    taxonomy9: Annotated[
        str | None, Field(description="Ninth-level product taxonomy category.", min_length=1)
    ] = None
    confidence: Annotated[
        float | None,
        Field(
            description="Confidence score when the line category or extraction was inferred.",
            ge=0.0,
            le=1.0,
        ),
    ] = None


class ExtractionMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    model: Annotated[str | None, Field(min_length=1)] = None
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    extracted_at: Annotated[AwareDatetime | None, Field(alias="extractedAt")] = None
    raw_text: Annotated[str | None, Field(alias="rawText")] = None


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(min_length=1)] = None
    source_document_id: Annotated[
        str | None,
        Field(
            alias="sourceDocumentId",
            description="Uploaded image, PDF or extraction job identifier.",
            min_length=1,
        ),
    ] = None
    receipt_number: Annotated[str | None, Field(alias="receiptNumber", min_length=1)] = None
    subtotal: Annotated[
        str | None,
        Field(
            description="Decimal amount encoded as a string to avoid floating point rounding errors.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    total: Annotated[
        str | None,
        Field(
            description="Signed receipt total. Usually matches transaction amount after normalization.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ] = None
    items: Annotated[list[ReceiptItem], Field(min_length=1)]
    extraction: ExtractionMetadata | None = None


class Transaction(BaseModel):
    """
    A canonical expense-tracking transaction, optionally enriched with receipt line items and category allocations.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[
        str,
        Field(
            description="Application-level stable identifier for this transaction.", min_length=1
        ),
    ]
    source: Annotated[Source, Field(description="How this transaction entered the system.")]
    external_id: Annotated[
        str | None,
        Field(
            alias="externalId",
            description="Importer-provided identifier, if one exists.",
            min_length=1,
        ),
    ] = None
    account_id: Annotated[
        str | None,
        Field(
            alias="accountId",
            description="Account that produced the statement row, when applicable.",
            min_length=1,
        ),
    ] = None
    transaction_date: Annotated[
        date, Field(alias="transactionDate", description="Date the transaction occurred.")
    ]
    posted_date: Annotated[
        date | None,
        Field(
            alias="postedDate",
            description="Date the transaction posted to the account, when different from the transaction date.",
        ),
    ] = None
    payee: Annotated[str, Field(description="Merchant, counterparty or payer name.", min_length=1)]
    description: Annotated[
        str | None, Field(description="Original or user-facing transaction description.")
    ] = None
    amount: Annotated[
        str,
        Field(
            description="Signed transaction amount from the account perspective.",
            pattern="^-?(0|[1-9][0-9]*)(\\.[0-9]{1,4})?$",
        ),
    ]
    currency: Annotated[str, Field(description="ISO 4217 currency code.", pattern="^[A-Z]{3}$")]
    kind: Annotated[Kind | None, Field(description="User-facing transaction kind.")] = None
    status: Status | None = Status.posted
    category_allocations: Annotated[
        list[CategoryAllocation] | None,
        Field(
            alias="categoryAllocations",
            description="Budget category splits for the transaction total.",
            validate_default=True,
        ),
    ] = []
    receipt: Annotated[
        Receipt | None, Field(description="Itemized receipt data associated with this transaction.")
    ] = None
    linked_transaction_ids: Annotated[
        list[NonEmptyString] | None,
        Field(
            alias="linkedTransactionIds",
            description="Other transaction records that represent the same real-world purchase, such as a receipt import matched to a statement row.",
        ),
    ] = []
    notes: str | None = None
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
